export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const LOGIN_SUCCES = "LOGIN_SUCCES";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const USER_SUCCES = "USER_SUCCES";
export const USER_FAIL = "USER_FAIL";

export const POSTS_SUCCES = "POSTS_SUCCES";
export const POSTS_FAIL = "POSTS_FAIL";

export const POST_SUCCES = "POST_SUCCES";
export const POST_FAIL = "POST_FAIL";

export const LIKE_POST = "LIKE_POST";

export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";

export const ADD_POST = "ADD_POST";
export const REMOVE_POST = "REMOVE_POST";

export const DELETE_USER_POST = "DELETE_USER_POST";

export const MESSAGE_SUCCES = "MESSAGE_SUCCES";
export const MESSAGE_FAIL = "MESSAGE_FAIL";

export const EDIT_TEACHER = "EDIT_TEACHER";

export const EDIT_PASSWORD = "EDIT_PASSWORD";

export const POSTPROF_SUCCES="POSTPROF_SUCCES"
export const POSTPROF_FAIL="POSTPROF_FAIL"

export const LIKE_POSTPROF="LIKE_POSTPROF"
export const ADD_COMMENTPROF="ADD_COMMENTPROF"
export const REMOVE_COMMENTPROF="REMOVE_COMMENTPROF"

export const GETPROF_ID="GETPROF_ID"
export const GETPROF_FAIL="GETPROF_FAIL"

export const PAGINATE_SUCCES="PAGINATE_SUCCES"
export const PAGINATE_FAIL="PAGINATE_FAIL"

export const LOGOUT = "LOGOUT";
